[lyrics-bot-playlister.lyrics]
root_url = "https://www.azlyrics.com"
song_list_url = "/n/national.html"
band_name = "The National"

[lyrics-bot-playlister.scraper]
sleep_time_seconds = 1

[lyrics-bot-playlister.twitter]
bot_name = "the_nationalbot"
register_webhook_url_base = "https://api.twitter.com/1.1/account_activity/all/prod/webhooks.json"
